spring.application.name=banking.app


# server configuration
server.port = 8080

# postgresql credentials
spring.datasource.url=jdbc:postgresql://localhost:5432/banking-system
spring.datasource.username=postgres
spring.datasource.password=salman
spring.datasource.driver-class-name=org.postgresql.Driver


#Spring Hibernate configuration 
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Properties to see table creation in the console
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.use_sql_comments=true
#spring.security.user.name=admin
#spring.security.user.password=admin123

# JWT Secret Key (For Authentication)
jwt.secret=xUiUVJ444B2tZ0A6HmXHhdCEiMiwQ1QEojurnPGbmvc=
jwt.expiration=86400000